[package]
name = "cam_dos"
version = "0.1.0"
authors = ["cam_dos_dev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.5.0"
